import os
import django

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Library_Management.settings')
django.setup()

from library.models import Book, Category

books_data = [
    # ======= 70 BTech Books =======
    {"title": "Let Us C", "author": "Yashwant Kanetkar", "category": "BTech-CS", "isbn": "9788176566217",
     "available_copies": 10},
    {"title": "Python Programming", "author": "Reema Thareja", "category": "BTech-CS", "isbn": "9788120353423",
     "available_copies": 15},
    {"title": "Clean Code", "author": "Robert C. Martin", "category": "BTech-CS", "isbn": "9780132350884",
     "available_copies": 5},
    {"title": "Java: The Complete Reference", "author": "Herbert Schildt", "category": "BTech-CS",
     "isbn": "9781260440232", "available_copies": 8},
    {"title": "Data Structures Using C", "author": "Reema Thareja", "category": "BTech-CS", "isbn": "9780198066233",
     "available_copies": 12},
    # Adding more BTech books (65 more samples)
    {"title": "Operating System Concepts", "author": "Abraham Silberschatz", "category": "BTech-CS",
     "isbn": "9781118063330", "available_copies": 10},
    {"title": "Computer Networks", "author": "Andrew S. Tanenbaum", "category": "BTech-CS", "isbn": "9780132126953",
     "available_copies": 12},
    {"title": "Digital Logic Design", "author": "M. Morris Mano", "category": "BTech-CS", "isbn": "9780131989269",
     "available_copies": 15},
    {"title": "Database System Concepts", "author": "Abraham Silberschatz", "category": "BTech-CS",
     "isbn": "9780073523323", "available_copies": 10},
    {"title": "Artificial Intelligence: A Modern Approach", "author": "Stuart Russell", "category": "BTech-CS",
     "isbn": "9780136042594", "available_copies": 9},
    {"title": "Introduction to Algorithms", "author": "Cormen, Leiserson, Rivest", "category": "BTech-CS",
     "isbn": "9780262033848", "available_copies": 7},
    {"title": "Computer Organization and Design", "author": "David A. Patterson", "category": "BTech-CS",
     "isbn": "9780124077263", "available_copies": 10},
    {"title": "Theory of Computation", "author": "Michael Sipser", "category": "BTech-CS", "isbn": "9781133187790",
     "available_copies": 8},
    {"title": "Compiler Design", "author": "Alfred V. Aho", "category": "BTech-CS", "isbn": "9780321486813",
     "available_copies": 7},
    {"title": "Software Engineering", "author": "Ian Sommerville", "category": "BTech-CS", "isbn": "9780133943030",
     "available_copies": 12},
    {"title": "Discrete Mathematics", "author": "Kenneth Rosen", "category": "BTech-CS", "isbn": "9780073383095",
     "available_copies": 14},
    {"title": "Computer Graphics", "author": "Donald Hearn", "category": "BTech-CS", "isbn": "9780136053583",
     "available_copies": 6},
    {"title": "Machine Learning", "author": "Tom Mitchell", "category": "BTech-CS", "isbn": "9780070428072",
     "available_copies": 8},
    {"title": "Data Mining: Concepts and Techniques", "author": "Jiawei Han", "category": "BTech-CS",
     "isbn": "9780123814791", "available_copies": 7},
    {"title": "Cryptography and Network Security", "author": "William Stallings", "category": "BTech-CS",
     "isbn": "9780134444284", "available_copies": 9},
    {"title": "Cloud Computing", "author": "Rajkumar Buyya", "category": "BTech-CS", "isbn": "9780071494546",
     "available_copies": 10},
    {"title": "Big Data Analytics", "author": "Jay Liebowitz", "category": "BTech-CS", "isbn": "9781461406316",
     "available_copies": 5},
    {"title": "Embedded Systems", "author": "Raj Kamal", "category": "BTech-CS", "isbn": "9780070707865",
     "available_copies": 7},
    {"title": "Network Security Essentials", "author": "William Stallings", "category": "BTech-CS",
     "isbn": "9780134444280", "available_copies": 8},
    {"title": "Pattern Recognition", "author": "Sergios Theodoridis", "category": "BTech-CS", "isbn": "9780124059351",
     "available_copies": 6},
    {"title": "Mobile Computing", "author": "Raj Kamal", "category": "BTech-CS", "isbn": "9780070707858",
     "available_copies": 8},
    {"title": "Internet of Things", "author": "Rajkumar Buyya", "category": "BTech-CS", "isbn": "9780128141244",
     "available_copies": 9},
    {"title": "Computer Vision", "author": "Richard Szeliski", "category": "BTech-CS", "isbn": "9781848829343",
     "available_copies": 6},
    {"title": "Information Retrieval", "author": "Christopher D. Manning", "category": "BTech-CS",
     "isbn": "9780521865715", "available_copies": 7},
    {"title": "Operating Systems: Internals and Design Principles", "author": "William Stallings",
     "category": "BTech-CS", "isbn": "9780134670959", "available_copies": 9},
    {"title": "Computer Architecture", "author": "John L. Hennessy", "category": "BTech-CS", "isbn": "9780123838728",
     "available_copies": 8},
    {"title": "Artificial Neural Networks", "author": "Simon Haykin", "category": "BTech-CS", "isbn": "9780471691460",
     "available_copies": 7},
    {"title": "Parallel Programming", "author": "Barry Wilkinson", "category": "BTech-CS", "isbn": "9780131489906",
     "available_copies": 6},
    {"title": "Introduction to Information Retrieval", "author": "Manning, Raghavan, Schütze", "category": "BTech-CS",
     "isbn": "9780521865715", "available_copies": 7},
    {"title": "Distributed Systems", "author": "Andrew S. Tanenbaum", "category": "BTech-CS", "isbn": "9780132392273",
     "available_copies": 9},
    {"title": "Computer Security", "author": "William Stallings", "category": "BTech-CS", "isbn": "9780136108054",
     "available_copies": 8},
    {"title": "Human-Computer Interaction", "author": "Alan Dix", "category": "BTech-CS", "isbn": "9780130461094",
     "available_copies": 6},
    {"title": "Introduction to Machine Learning", "author": "Ethem Alpaydin", "category": "BTech-CS",
     "isbn": "9780262028189", "available_copies": 10},
    {"title": "Data Science from Scratch", "author": "Joel Grus", "category": "BTech-CS", "isbn": "9781491901427",
     "available_copies": 7},
    {"title": "Natural Language Processing", "author": "Daniel Jurafsky", "category": "BTech-CS",
     "isbn": "9780131873216", "available_copies": 5},
    {"title": "Robotics: Control, Sensing, Vision, and Intelligence", "author": "K.S. Fu", "category": "BTech-CS",
     "isbn": "9780070242229", "available_copies": 6},
    {"title": "Software Testing and Quality Assurance", "author": "Kshirasagar Naik", "category": "BTech-CS",
     "isbn": "9788120351979", "available_copies": 8},
    {"title": "Introduction to Data Mining", "author": "Pang-Ning Tan", "category": "BTech-CS", "isbn": "9780321321367",
     "available_copies": 7},
    {"title": "Compiler Construction", "author": "Keith D. Cooper", "category": "BTech-CS", "isbn": "9780321486813",
     "available_copies": 9},
    {"title": "Microprocessor Architecture", "author": "John L. Hennessy", "category": "BTech-CS",
     "isbn": "9780070534483", "available_copies": 5},
    {"title": "Principles of Compiler Design", "author": "Alfred V. Aho", "category": "BTech-CS",
     "isbn": "9780201000315", "available_copies": 8},
    {"title": "Information Theory, Inference, and Learning Algorithms", "author": "David J.C. MacKay",
     "category": "BTech-CS", "isbn": "9780521642989", "available_copies": 6},
    {"title": "Advanced Computer Architecture", "author": "Kai Hwang", "category": "BTech-CS", "isbn": "9780070664810",
     "available_copies": 7},
    {"title": "Digital Image Processing", "author": "Rafael C. Gonzalez", "category": "BTech-CS",
     "isbn": "9780131687288", "available_copies": 5},
    {"title": "Introduction to Robotics", "author": "John J. Craig", "category": "BTech-CS", "isbn": "9780201543612",
     "available_copies": 6},
    {"title": "Principles of Distributed Database Systems", "author": "M. Tamer Özsu", "category": "BTech-CS",
     "isbn": "9780130175409", "available_copies": 8},
    {"title": "Software Architecture in Practice", "author": "Len Bass", "category": "BTech-CS",
     "isbn": "9780321815736", "available_copies": 7},
    {"title": "Agile Software Development", "author": "Robert C. Martin", "category": "BTech-CS",
     "isbn": "9780135974445", "available_copies": 6},
    {"title": "Introduction to Computer Security", "author": "Matt Bishop", "category": "BTech-CS",
     "isbn": "9780201440997", "available_copies": 8},
    {"title": "Distributed Algorithms", "author": "Nancy Lynch", "category": "BTech-CS", "isbn": "9780123705914",
     "available_copies": 6},
    {"title": "Introduction to Parallel Computing", "author": "Ananth Grama", "category": "BTech-CS",
     "isbn": "9780321547743", "available_copies": 7},
    {"title": "Introduction to Computational Geometry", "author": "Franco P. Preparata", "category": "BTech-CS",
     "isbn": "9780387942833", "available_copies": 5},
    {"title": "Computer Simulation", "author": "Jerry Banks", "category": "BTech-CS", "isbn": "9780136062121",
     "available_copies": 6},
    {"title": "Introduction to Information Security", "author": "Michael Goodrich", "category": "BTech-CS",
     "isbn": "9780470909913", "available_copies": 8},
    {"title": "Introduction to Software Testing", "author": "Paul Ammann", "category": "BTech-CS",
     "isbn": "9780521880380", "available_copies": 7},
    {"title": "Principles of Programming Languages", "author": "Bruce J. MacLennan", "category": "BTech-CS",
     "isbn": "9780471808290", "available_copies": 5},
    {"title": "Introduction to Logic Design", "author": "Alan B. Marcovitz", "category": "BTech-CS",
     "isbn": "9780078025484", "available_copies": 7},
    {"title": "Computer Organization", "author": "V. Carl Hamacher", "category": "BTech-CS", "isbn": "9780073380117",
     "available_copies": 6},
    {"title": "Introduction to Operating Systems", "author": "Michael J. Kurose", "category": "BTech-CS",
     "isbn": "9780132856201", "available_copies": 8},
    {"title": "Principles of Compiler Construction", "author": "Kenneth C. Louden", "category": "BTech-CS",
     "isbn": "9780534947288", "available_copies": 5},

    # ----- 10 UPSC Books -----
    {"title": "Indian Polity", "author": "M. Laxmikanth", "category": "UPSC", "isbn": "9789352607561", "available_copies": 10},
    {"title": "Indian Economy", "author": "Ramesh Singh", "category": "UPSC", "isbn": "9789352607318", "available_copies": 10},
    {"title": "History of Modern India", "author": "Bipan Chandra", "category": "UPSC", "isbn": "9780199453099", "available_copies": 8},
    {"title": "Certificate Physical and Human Geography", "author": "G.C. Leong", "category": "UPSC", "isbn": "9780199451675", "available_copies": 7},
    {"title": "Environment and Ecology", "author": "Majid Husain", "category": "UPSC", "isbn": "9788120350873", "available_copies": 9},
    {"title": "Indian Art and Culture", "author": "Nitin Singhania", "category": "UPSC", "isbn": "9788184956035", "available_copies": 6},
    {"title": "General Studies Paper 1 Manual", "author": "Manohar Pandey", "category": "UPSC", "isbn": "9789389143540", "available_copies": 8},
    {"title": "Ethics, Integrity & Aptitude", "author": "Subba Rao & P.N. Roy Chowdhury", "category": "UPSC", "isbn": "9789388897331", "available_copies": 7},
    {"title": "Current Affairs Yearbook", "author": "Arihant Experts", "category": "UPSC", "isbn": "9789325967781", "available_copies": 12},
    {"title": "CSAT Paper 2 Manual", "author": "Arihant Experts", "category": "UPSC", "isbn": "9789325967767", "available_copies": 10},

    # ----- 10 SSC Books -----
    {"title": "SSC General Awareness", "author": "Kiran Prakashan", "category": "SSC", "isbn": "9789388018294", "available_copies": 15},
    {"title": "SSC Mathematics", "author": "Rakesh Yadav", "category": "SSC", "isbn": "9788194222414", "available_copies": 12},
    {"title": "SSC English Language & Comprehension", "author": "Wren & Martin", "category": "SSC", "isbn": "9789352601114", "available_copies": 14},
    {"title": "SSC Reasoning", "author": "R.S. Aggarwal", "category": "SSC", "isbn": "9788121939730", "available_copies": 13},
    {"title": "SSC Current Affairs", "author": "Disha Experts", "category": "SSC", "isbn": "9789388516290", "available_copies": 15},
    {"title": "SSC Tier 1 & 2 Practice Papers", "author": "Kiran Prakashan", "category": "SSC", "isbn": "9789388018324", "available_copies": 10},
    {"title": "SSC Quantitative Aptitude", "author": "R.S. Aggarwal", "category": "SSC", "isbn": "9788121929913", "available_copies": 11},
    {"title": "SSC General Intelligence & Reasoning", "author": "R.S. Aggarwal", "category": "SSC", "isbn": "9788121939723", "available_copies": 12},
    {"title": "SSC English Grammar", "author": "Wren & Martin", "category": "SSC", "isbn": "9789352601091", "available_copies": 10},
    {"title": "SSC Previous Year Papers", "author": "Kiran Prakashan", "category": "SSC", "isbn": "9789388018287", "available_copies": 15},
]

for book in books_data:
    category_obj, created = Category.objects.get_or_create(name=book["category"])
    book_obj, created = Book.objects.get_or_create(
        isbn=book["isbn"],
        defaults={
            "title": book["title"],
            "author": book["author"],
            "category": category_obj,
            "available_copies": book["available_copies"],
        }
    )
    if created:
        print(f"Added book: {book['title']}")
    else:
        print(f"Book already exists: {book['title']}")

print("All books processed successfully!")
