services:
  - type: web
    name: library-management-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Library_Management.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Library_Management.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DEBUG
        value: False
    staticPublishPath: staticfiles
